[build]
	command = "npm run build"
	publish = "dist"
	functions = "functions"

[dev]
	command = "npm run netlify"
	functions = "functions"
	publish = "dist"
	targetPort = 8888
	port= 8080
	framework = "#custom"

[[redirects]]
	from = "/:slug"
	to = "/.netlify/functions/test"
	status = 200	